[package]
name = "rustsdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.8.1"
async-trait = "0.1.68"
hashed_wheel_timer = "0.1.1"
bytes = { version = "1", features = ["serde"] }