pub(crate) enum QueryMode {
    SINGLE,
    BOUNDEDCLIENTSTREAM,
    CONTINOUSCLIENTSTREAM,
    BOUNDEDSERVERSYNCSTREAM,
    CONTINOUSSERVERSYNCSTREAM,
    BOUNDEDSERVERASYNCSTREAM,
    CONTINOUSSERVERASYNCSTREAM,
    VALIDATE,
}
